services:
  - type: web
    name: po-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1
